- listenport: 25565
  mac_address: "XX:XX:XX:XX:XX:XX"
  target_ip: "192.168.1.100"
  target_port: 25565

- listenport: 8096
  mac_address: "XX:XX:XX:XX:XX:XX"
  target_ip: "192.168.1.100"
  target_port: 8096
