name: Powersafe TCP Proxy
version: "0.1.0"
slug: powersafe_tcp
description: TCP proxy with HA automation trigger
startup: application
boot: auto
host_network: true
arch:
  - amd64
  - aarch64
  - armv7

options:
  proxies:
    - listenport: 1234
      target_ip_proxy: 192.168.1.999
      target_port_proxy: 1234
      target_ip_regions:
        - Region1
        - Region2
      local_only: false
      client_timeout: 60
      ha_url: http://homeassistant.local
      ha_token: your_long_lived_access_token
      ha_automation_id: automation.example_automation_id

schema:
  proxies:
    - map
    - listenport: int
      target_ip_proxy: str
      target_port_proxy: int
      target_ip_regions:
        - str
      local_only: bool
      client_timeout: int
      ha_url: str
      ha_token: str
      ha_automation_id: str
